name: deploy to tomcat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    #runs-on: ubuntu-latest
     runs-on: self-hosted
     steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: install maven 
        run: |
            yum install maven -y

      - name: build war using maven
        run: mvn clean package

      - name: Deploy WAR to Tomcat
        run: |
              WAR_FILE=$(ls target/*.war | head -n 1)
              APP_NAME=mcapp
              curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
                --upload-file "$WAR_FILE" \
                "http://${{ secrets.TOMCAT_HOST }}:8081/manager/text/deploy?path=/$APP_NAME&update=true"

 
      
